"""Pull the shared-chrome rules (header, footer, logo, project cards, buttons) out of index.html
into css/pages.css so the inner pages look identical. Re-run after changing those styles on the homepage."""
import re
s=open('index.html').read()
css='\n'.join(re.findall(r'<style[^>]*>(.*?)</style>',s,re.S))
css=re.sub(r'/\*.*?\*/','',css,flags=re.S)
KEEP=re.compile(r'(^|[\s,>+~(])(:root|html|body|\*|a|img|h[1-6]|p|ul|button|\.site-head|\.nav|\.wordmark|\.wm\b|\.mark|footer|\.site-foot|\.f-|\.ft|\.soc|\.wrap|\.pc|\.proj-list|\.proj-more|\.ba|\.proof|\.cta|\.wa-fab|\.sr-only|\.ic\b|\.b-amber|\.btn)')
DROP=re.compile(r'\.d-|\.descent|\.intro|\.qd|\.hero|\.sx-|section\b')
def blocks(t):
    i=0;out=[]
    while i<len(t):
        j=t.find('{',i)
        if j<0:break
        sel=t[i:j].strip();d=1;k=j+1
        while d and k<len(t):
            if t[k]=='{':d+=1
            elif t[k]=='}':d-=1
            k+=1
        out.append((sel,t[j+1:k-1]));i=k
    return out
def keep(sel):
    parts=[p.strip() for p in sel.split(',')]
    good=[p for p in parts if KEEP.search(' '+p) and not DROP.search(p)]
    return ','.join(good)
res=[]
for sel,body in blocks(css):
    if sel.startswith('@keyframes'):
        if re.search(r'wa|In\b|waIn|waPulse',sel):res.append(f'{sel}{{{body}}}')
        continue
    if sel.startswith('@media') or sel.startswith('@supports'):
        inner=[f'{k}{{{b}}}' for x,b in blocks(body) if (k:=keep(x))]
        if inner:res.append(sel+'{'+''.join(inner)+'}')
        continue
    if sel.startswith('@'):continue
    k=keep(sel)
    if k:res.append(f'{k}{{{body.strip()}}}')
open('css/pages.css','w').write('/* generated by tools/extract_css.py from index.html */\n'+'\n'.join(res)+'\n')
print(len(res),'rules')
